services:
  app:
    image: containrrr/watchtower
    container_name: "watchtower"
    restart: always
    command:
      - "--cleanup=true"
      - "--label-enable"
      - "--interval"
      - "60"
      - "--rolling-restart"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock